# Generated by Django 4.0.4 on 2022-05-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('name2', models.CharField(max_length=150, verbose_name='фамилия')),
                ('name3', models.CharField(blank=True, max_length=150, verbose_name='отчество')),
                ('age', models.IntegerField()),
                ('sex', models.BooleanField(verbose_name='пол (True-мужской)')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='наименование')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
            ],
        ),
    ]
